### ISSUE TITLE
Som.py usage

### ISSUE THREAD

**Issue by FriederikeHanssen** [zic12345/SR2019#1]
Hi!
I just read your paper, and I am actually wondering how you ran som.py. I couldn't find the script in the repository, could you make it available?

**Comment by zic12345** [comment]
Hello!
The script has been uploaded.

**Comment by faruqsandi** [comment]
hello! it is still missing.

**Comment by FriederikeHanssen** [comment]
See here: https://github.com/zic12345/SR2019/blob/master/7.run_sompy.sh
